version: '3.8'

services:
  smart-warehouse:
    build: .
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - ./python_backend:/app/python_backend:ro
      - ./frontend:/app/frontend:ro
